### ISSUE TITLE
"jctl computers -d -s general/last_contact_time~=2021" leads to ValueError

### ISSUE THREAD

**Issue by venkman-gh** [univ-of-utah-marriott-library-apple/jctl#48]
I'm trying to delete computers that did not contacted our Jamf Pro instance since 2020 and 2021. I'm running jctl 1.1.15 with python_jamf 0.7.4. In my case I could run the following line successfully;

`jctl computers -d -s general/last_contact_time~=2021`

But the following line exited with a ValueError:

`jctl computers -d -s general/last_contact_time~=2020`

Here's the stack trace;

`Traceback (most recent call last):
  File "/usr/local/bin/jctl", line 559, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/jctl", line 389, in main
    path_data = record.get_path(m[1])
  File "/Library/Python/3.8/site-packages/jamf/records.py", line 508, in get_path
    self.refresh()
  File "/Library/Python/3.8/site-packages/jamf/records.py", line 449, in refresh
    results = self.api.get(end)
  File "/Library/Python/3.8/site-packages/jamf/api.py", line 193, in get
    self.set_session_auth()
  File "/Library/Python/3.8/site-packages/jamf/api.py", line 154, in set_session_auth
    deadline = datetime.strptime(expires.split('.')[0], '%Y-%m-%dT%H:%M:%S')
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: Z`

**Comment by magnusviri** [comment]
Sorry for taking so long to get to this. We've actually fixed this. I thought we put this in the latest release but we haven't released a new version since we fixed it. I'll work on getting it updated.

**Comment by magnusviri** [comment]
I've released the fix. The bug was in [python-jamf](https://github.com/univ-of-utah-marriott-library-apple/python-jamf), so that's what was updated.
